name: text_recognition
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Botton Navigation Bar Formatting
  bubble_bottom_bar: ^1.2.0

  #Firebase Vision
  firebase_ml_vision: ^0.9.9
  image_picker: ^0.6.7+14

  clipboard: ^0.1.2+8

  #Translator
  dropdownfield: ^1.0.3
  translator: ^0.1.5
  html_unescape: ^1.0.2

  #Text To Speech
  flutter_tts: ^1.3.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/book.png

  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: fonts/OpenDyslexic-Regular.ttf
